// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscribers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmSubscriber = `-- name: ConfirmSubscriber :one
UPDATE subscribers
SET confirmed = TRUE, token = NULL, updated_at = NOW()
WHERE token = $1
RETURNING id, email, name, confirmed, token, created_at, updated_at
`

func (q *Queries) ConfirmSubscriber(ctx context.Context, token pgtype.Text) (Subscriber, error) {
	row := q.db.QueryRow(ctx, confirmSubscriber, token)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Confirmed,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (email, name, token)
VALUES ($1, $2, $3)
RETURNING id, email, name, confirmed, token, created_at, updated_at
`

type CreateSubscriberParams struct {
	Email string
	Name  pgtype.Text
	Token pgtype.Text
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber, arg.Email, arg.Name, arg.Token)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Confirmed,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers
WHERE email = $1
`

func (q *Queries) DeleteSubscriber(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, email)
	return err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, name, confirmed, token, created_at, updated_at FROM subscribers
WHERE email = $1
`

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Confirmed,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByToken = `-- name: GetSubscriberByToken :one
SELECT id, email, name, confirmed, token, created_at, updated_at FROM subscribers
WHERE token = $1
`

func (q *Queries) GetSubscriberByToken(ctx context.Context, token pgtype.Text) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByToken, token)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Confirmed,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfirmedSubscribers = `-- name: ListConfirmedSubscribers :many
SELECT id, email, name, confirmed, token, created_at, updated_at FROM subscribers
WHERE confirmed = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListConfirmedSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listConfirmedSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Confirmed,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
